from django.urls import path
from books.views import RoomLeaseList, RoomDealingList, RoomLeaseCreating, RoomLeaseDeatil, RoomLeaseUpdate, roomlease_search, roomlease_delete, StoreLeaseList, StoreLeaseDeatil, StoreLeaseCreating, StoreLeaseUpdate, storelease_search, storelease_delete, RoomDealingDeatil, RoomDealingUpdate, roomdealing_delete, roomdealing_search, RoomDealingCreating, BuildingDealingList, BuildingDealingDeatil, BuildingDealingUpdate, buildingdealing_delete, buildingdealing_search, BuildingDealingCreating

app_name = 'books'

urlpatterns = [
    path("room-lease/", RoomLeaseList.as_view(), name="room-lease-list"),
    path("room-lease/<int:pk>/", RoomLeaseDeatil.as_view(),
         name="room-lease-detail"),
    path("room-lease/<int:pk>/update/",
         RoomLeaseUpdate.as_view(), name="room-lease-update"),
    path("room-lease/<int:pk>/delete/",
         roomlease_delete, name="room-lease-delete"),
    path("room-lease/search/", roomlease_search, name="room-lease-search"),
    path("room-lease/creating/", RoomLeaseCreating.as_view(),
         name="room-lease-creating"),
    path("room-dealing/", RoomDealingList.as_view(), name="room-dealing-list"),
    path("room-dealing/<int:pk>/", RoomDealingDeatil.as_view(),
         name="room-dealing-detail"),
    path("room-dealing/<int:pk>/update/",
         RoomDealingUpdate.as_view(), name="room-dealing-update"),
    path("room-dealing/<int:pk>/delete/",
         roomdealing_delete, name="room-dealing-delete"),
    path("room-dealing/search/", roomdealing_search, name="room-dealing-search"),
    path("room-dealing/creating/", RoomDealingCreating.as_view(),
         name="room-dealing-creating"),
    path("store-lease/", StoreLeaseList.as_view(), name="store-lease-list"),
    path("store-lease/<int:pk>/", StoreLeaseDeatil.as_view(),
         name="store-lease-detail"),
    path("store-lease/creating/", StoreLeaseCreating.as_view(),
         name="store-lease-creating"),
    path("store-lease/<int:pk>/update/",
         StoreLeaseUpdate.as_view(), name="store-lease-update"),
    path("store-lease/search/", storelease_search, name="store-lease-search"),
    path("store-lease/<int:pk>/delete/",
         storelease_delete, name="store-lease-delete"),
    path("building-dealing/", BuildingDealingList.as_view(),
         name="building-dealing-list"),
    path("building-dealing/<int:pk>/", BuildingDealingDeatil.as_view(),
         name="building-dealing-detail"),
    path("building-dealing/<int:pk>/update/",
         BuildingDealingUpdate.as_view(), name="building-dealing-update"),
    path("building-dealing/<int:pk>/delete/",
         buildingdealing_delete, name="building-dealing-delete"),
    path("building-dealing/search/", buildingdealing_search,
         name="building-dealing-search"),
    path("building-dealing/creating/", BuildingDealingCreating.as_view(),
         name="building-dealing-creating"),
]
