# Generated by Django 3.1.4 on 2021-03-26 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingDealingCustomer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_phone', models.CharField(max_length=30)),
                ('updated', models.DateField(auto_now=True)),
                ('price', models.IntegerField(default=0)),
                ('elevator', models.BooleanField()),
                ('not_finished', models.BooleanField(default=True)),
                ('finished', models.BooleanField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='HouseDealingCustomer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_phone', models.CharField(max_length=30)),
                ('updated', models.DateField(auto_now=True)),
                ('price', models.IntegerField(default=0)),
                ('room', models.IntegerField(default=0)),
                ('area_m2', models.IntegerField(default=0)),
                ('parking', models.BooleanField()),
                ('elevator', models.BooleanField()),
                ('not_finished', models.BooleanField(default=True)),
                ('finished', models.BooleanField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='HouseLeaseCustomer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_phone', models.CharField(max_length=30)),
                ('updated', models.DateField(auto_now=True)),
                ('deposit', models.IntegerField(default=0)),
                ('month_fee', models.IntegerField(default=0)),
                ('room', models.IntegerField(default=0)),
                ('area_m2', models.IntegerField(default=0)),
                ('parking', models.BooleanField(default=False)),
                ('elevator', models.BooleanField(default=False)),
                ('loan', models.BooleanField(default=False)),
                ('not_finished', models.BooleanField(default=True)),
                ('finished', models.BooleanField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ShopLeaseCustomer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_phone', models.CharField(max_length=30)),
                ('updated', models.DateField(auto_now=True)),
                ('deposit', models.IntegerField(default=0)),
                ('month_fee', models.IntegerField(default=0)),
                ('area_m2', models.IntegerField(default=0)),
                ('parking', models.BooleanField(default=False)),
                ('elevator', models.BooleanField(default=False)),
                ('not_finished', models.BooleanField(default=True)),
                ('finished', models.BooleanField()),
                ('description', models.TextField()),
            ],
        ),
    ]
